name: quadb_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  crystal_navigation_bar: ^1.0.0
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  iconly: ^1.0.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - asset/
